version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"

  schedule_webserver:
    image: schedule_service:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    command: sh -c "python manage.py makemigrations snippets && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
# need to set befor lunch
    environment:
      - TELEGRAM_CHAT_ID
      - TELEGRAM_TOKEN
    ports:
      - "8000:8000"
    expose:
      - "5432"

  allure-docker-service:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"

  autotests:
    image: "autotest:latest"
    depends_on:
      - postgres
      - allure-docker-service
      - schedule_webserver
    expose:
      - "5050"
      - "5000"